[package]
name = "eff"
version = "0.0.7"
authors = ["pan"]
edition = "2018"

description = "Algebraic Effects Library for Rust"
repository = "https://github.com/pandaman64/effective-rust/"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
eff-attr = "0.0.6"
proc-macro-hack = "0.5.4"
pin-utils = "0.1.0-alpha.4"
log = "0.4.6"

[dev-dependencies]
clap = "2.33"

[workspace]
members = [
    "./",
    "eff-attr",
]
